name: Despliegue de la pagina web del UEPJMC

on:
  push:
    branches: ["main"]


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Crear y desplegar el contenedor Docker
        run: docker-compose -f docker-compose-deploy.yml up -d --build
      - name: limpiando file deploy
        run: rm -rf *
